import assert from 'node:assert/strict';
import {buildWorkbook} from '../src/resources/workbookPdf.js';
import {validatePack,latestAoa} from '../src/resources/activityPack.js';
const pack={title:'Where Is Your Book?',grade:'Kinder',skill:'Listening',lessonTitle:'Classroom objects and locations',activities:[{type:'picture_choice',title:'Listen and circle',instruction:'Listen to your teacher. Circle the picture.',items:[{teacherPrompt:'The book is on the desk.',options:[{icon:'book',position:'on',anchor:'desk',label:'Book on the desk'},{icon:'book',position:'under',anchor:'desk',label:'Book under the desk'}],answerIndex:0},{teacherPrompt:'Show me the bag.',options:[{icon:'bag',label:'Bag'},{icon:'chair',label:'Chair'}],answerIndex:0}]},{type:'match',title:'Find the classroom objects',instruction:'With your teacher, match each picture to its word.',items:[{icon:'book',word:'book'},{icon:'bag',word:'bag'},{icon:'chair',word:'chair'}]},{type:'draw_write',title:'Draw and tell',instruction:'Draw your classroom.',prompt:'Draw a book on a desk. Point and tell your teacher.',teacherGuide:'Accept a drawing with a book on the desk. Ask the child to point to the book.'}],rubric:[{criterion:'Recognizes classroom objects',independent:'Points to the named object independently.',withSupport:'Points after a repeated prompt.',emerging:'Needs a model and guided practice.'},{criterion:'Understands on and under',independent:'Chooses the correct location.',withSupport:'Chooses with gesture support.',emerging:'Needs demonstration.'}]};
assert.equal(latestAoa([{type:'resources',createdAt:'2026-09-15'},{id:'correct',type:'planner',createdAt:'2026-09-14'}]).id,'correct');
assert.throws(()=>validatePack({...pack,activities:[]}));
const invalid=structuredClone(pack);invalid.activities[0].items[0].answerIndex=99;assert.throws(()=>validatePack(invalid));
const doc=buildWorkbook(pack);assert.equal(doc.getNumberOfPages(),8);
console.log('Schema, source selection and 8-page PDF checks passed.');

const older = structuredClone(pack); older.grade='12th Grade'; older.activities=[{type:'read_answer',title:'Read and reflect',instruction:'Read and answer.',passage:'Students organize a school recycling campaign.',questions:[{question:'What do students organize?',answer:'A school recycling campaign.'}]},pack.activities[2]]; assert.ok(buildWorkbook(older).getNumberOfPages() >= 6);
