import { parseAoaLessonPlan } from '../src/resources/lessonParser.js';
import { renderWorkbookHtml } from '../src/resources/renderWorkbookHtml.js';

// What if the planner HTML generated by Gemini looked like this:
const htmlFromGemini = `
<div class="planner-container">
  <h1>Lesson Planner – Theme # How Much Is the Pineapple? – Lesson # 3</h1>
  <p>Kindergarten teachers love using interactive activities...</p>
  <table>
    <tr><td>Lesson #: 3</td><td>Skills Focus: Speaking</td></tr>
    <tr><td>Grade: 4th Grade (CEFR: A1)</td><td>Scenario: Shopping at the Market</td><td>Theme: How Much Is the Pineapple?</td></tr>
  </table>
  <h3>Stage 1 — Warm-up</h3>
  <p><strong>The teacher models the target language for asking about price</strong></p>
  <p><strong>Describing quantity</strong></p>
  <p><strong>Pineapple</strong>, <strong>Banana</strong>, <strong>Orange</strong>, <strong>Apple</strong></p>
</div>
`;

// Test with empty metadata
const parsedWithoutMetadata = parseAoaLessonPlan(htmlFromGemini, {});
console.log('Without metadata:');
console.log('  title:', parsedWithoutMetadata.title);
console.log('  grade:', parsedWithoutMetadata.grade);
console.log('  skill:', parsedWithoutMetadata.skill);
console.log('  action items:', parsedWithoutMetadata.actionWorksheet.part1.items.map(i => i.word));

const rendered = renderWorkbookHtml(parsedWithoutMetadata);
console.log('  Rendered includes Kindergarten?:', rendered.includes('Kindergarten'));
const match = rendered.match(/<p class="text-xs font-bold text-emerald-700[^"]*">([\s\S]*?)<\/p>/);
console.log('  Grade badge line:', match ? match[1].trim() : 'NONE');
