import {useRef,useState} from 'react';
import {classroomPosterHtml,fitClassroomPoster} from '../resources/classroomPoster';

export default function ScenarioPoster({grade,scenario,index,ready,cefr=''}) {
  const [poster,setPoster]=useState(null),[fits,setFits]=useState(false),[error,setError]=useState('');
  const frame=useRef(null);
  const create=()=>{try{setFits(false);setError('');setPoster({html:classroomPosterHtml(scenario,grade,index,cefr),grade,index});}catch{setError('No se pudo preparar el póster de este escenario.');}};
  const loaded=async()=>{const ok=await fitClassroomPoster(frame.current.contentDocument);setFits(ok);if(!ok)setError('El contenido no cabe de forma legible en una página. La impresión se ha bloqueado para evitar recortes.');};
  const print=async()=>{if(!frame.current)return;const ok=await fitClassroomPoster(frame.current.contentDocument);if(!ok){setFits(false);setError('El contenido excede una página.');return;}frame.current.contentWindow.focus();frame.current.contentWindow.print();};
  return <section className="mt-5 p-5 rounded-2xl border border-teal-400/30 bg-gradient-to-br from-teal-500/10 to-indigo-500/10"><h2 className="font-bold text-lg text-teal-700 dark:text-teal-300">Crear póster Scenario</h2><p className="text-sm my-3">Carta · 8½ × 11 pulgadas · margen de 1 cm · una página.</p><p className="text-xs text-slate-500 my-3">Vocabulario visual, categorías, preguntas y conversación del grado y escenario seleccionados.</p><button disabled={!ready} onClick={create} className="w-full bg-teal-600 text-white p-3 rounded-xl font-bold disabled:opacity-40">CREAR PÓSTER DE AULA</button>{error&&<p role="alert" className="text-red-500 my-3">{error}</p>}{poster&&<div className="fixed inset-0 z-[100] bg-slate-950/90 p-4 overflow-auto" role="dialog" aria-modal="true" aria-label="Póster de aula"><div className="max-w-5xl mx-auto rounded-2xl bg-white dark:bg-slate-900 p-5"><div className="flex justify-between gap-4 items-center mb-4"><h2>{poster.grade} · Escenario {poster.index+1}</h2><div className="flex gap-3"><button disabled={!fits} onClick={print} className="px-4 py-2 rounded-xl bg-teal-600 text-white disabled:opacity-40">Imprimir / Guardar PDF</button><button onClick={()=>setPoster(null)}>Cerrar</button></div></div><p className="text-sm mb-4">En impresión, selecciona Guardar como PDF, papel Carta, escala 100% y desactiva encabezados y pies del navegador.</p>{error&&<p role="alert" className="text-red-500 mb-3">{error}</p>}<iframe ref={frame} onLoad={loaded} title="Póster Carta de una página" srcDoc={poster.html} sandbox="allow-same-origin allow-modals" className="w-full h-[75vh] border-0 bg-white"/></div></div>}</section>;
}
